name: Update-Policy

on:
  schedule:
    - cron: "0 0 1 */1 *" # At 00:00 on day-of-month 1 in every month
  workflow_dispatch:

jobs:
  update_k8sapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Update k8sapi package
        run: go run tools/gen_api_list/gen_api_list.go
      - name: Set up Git configuration
        run: |
          git config --local user.email "36035885+x-color@users.noreply.github.com"
          git config --local user.name "x-color"
      - name: Commit updated k8spi
        run: |
          git add k8sapi
          git diff --cached --quiet || git commit -m "Update k8sapi"
      - name: Generate policy files
        run: go run main.go
      - name: Commit new policy file
        run: |
          git add policy
          git diff --cached --quiet || git commit -m "Update policy file"
      - name: Push changes
        run: |
          if [[ `git rev-parse HEAD` == `git rev-parse origin/main` ]]; then
            git push origin main
          fi
